kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.nginx.name }}-config
  labels:
    app: {{ .Values.nginx.name }}-proxy
data:
  nginx.conf: |
    events { }
    pid nginx.pid;
    http {
      server_tokens off;
      large_client_header_buffers 4 40k;
      server {
        listen {{ .Values.nginx.port }};
        include /etc/nginx/mime.types;
        location / {
          proxy_pass {{ .Values.nginx.keycloak.url }};
        }
      }
    }
